pipeline {
    agent any
    environment {
        FRONTEND_IMAGE = 'maryam197/mynewimage:latest'
    }
    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
        stage('Build Frontend') {
            steps {
                script {
                    sh 'docker build -t $FRONTEND_IMAGE ./frontend'
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    sh 'docker run --rm $FRONTEND_IMAGE npm test'
                }
            }
        }
        stage('Deploy Frontend') {
            steps {
                script {
                    sh 'docker run -d --name frontend -p 80:80 $FRONTEND_IMAGE'
                }
            }
        }
    }
    post {
        always {
            echo 'Cleaning up...'
            sh 'docker rm -f $(docker ps -aq)'
        }
    }
}
